--- 
# - name: Install
#   ansible.builtin.package:
#     name:
#       - timedatectl
#     state: latest
#   become: yes

- name: Enable NTP time synchronisation
  ansible.builtin.shell:
    cmd: timedatectl set-ntp true
  become: yes
