---
- name: Create a directory if it does not exists
  ansible.builtin.file:
    path: "{{ ansible_user_dir }}/.local/bin"
    state: directory
    mode: '0755'

- name: Copy dotfiles
  ansible.builtin.copy:
    dest: "{{ ansible_user_dir }}/.local/bin/dotfiles"
    src: "{{ playbook_dir }}/bin/dotfiles"
    mode: '0744'
