---
- name: Copy cheat
  ansible.builtin.copy:
    dest: "{{ ansible_user_dir }}/.local/scripts/cheat"
    src: "cheat"

- name: Copy tmux-sessionizer
  ansible.builtin.copy:
    dest: "{{ ansible_user_dir }}/.local/scripts/tmux-sessionizer"
    src: "tmux-sessionizer"
