---
- name: Copy ZSHRC
  ansible.builtin.copy:
    dest: "{{ ansible_user_dir }}/.zshrc"
    src: "zshrc"
    mode: '0744'

- name: Reload shell configuration with Zsh
  ansible.builtin.shell: zsh -c "source {{ ansible_user_dir }}/.zshrc"

