---
- name: "Include macOS tasks"
  include_tasks: "{{ role_path }}/tasks/macos.yaml"
  when: ansible_os_family == "Darwin"

# - name: "Include Debian tasks"
#   include_tasks: "{{ role_path }}/tasks/debian.yaml"
#   when: ansible_os_family == "Debian"
#
# - name: "Include RedHat tasks"
#   include_tasks: "{{ role_path }}/tasks/redhat.yaml"
#   when: ansible_os_family == "RedHat"
#
# - name: "Include Arch Linux tasks"
#   include_tasks: "{{ role_path }}/tasks/archlinux.yaml
#   when: ansible_distribution == "Archlinux"

- name: Copy ZSHRC
  ansible.builtin.copy:
    dest: "{{ ansible_user_dir }}/.zshrc"
    src: "zshrc"
    mode: '0744'

# - name: Reload shell configuration with Zsh
#   ansible.builtin.shell: zsh -c "source {{ ansible_user_dir }}/.zshrc"

- name: Copy p10k.zsh configuration file
  ansible.builtin.copy:
    dest: "{{ ansible_user_dir }}/.p10k.zsh"
    src: "p10k.zsh"
    mode: '0744'

