---
- name: Install wmctrl
  pacman:
    name: wmctrl
    state: present

- name: Create script to open terminal and Firefox on specific workspaces
  copy:
    dest: /usr/local/bin/open_apps.sh
    content: |
      #!/bin/bash

      export DISPLAY=:0
      export XAUTHORITY={{ ansible_user_dir }}/.Xauthority

      # Open terminal in workspace 1
      gnome-terminal &
      sleep 5
      wmctrl -r :ACTIVE: -t 0
      sleep 1
      wmctrl -r :ACTIVE: -b add,fullscreen

      # Open Firefox in workspace 2
      firefox &
      sleep 5
      wmctrl -r :ACTIVE: -t 1
      sleep 1
      wmctrl -r :ACTIVE: -b add,fullscreen
    mode: '0755'
  become: yes

- name: Create autostart directory if it doesn't exist
  file:
    path: "{{ ansible_user_dir }}/.config/autostart"
    state: directory
    mode: '0755'

- name: Enable open_apps.sh on startup
  copy:
    dest: "{{ ansible_user_dir }}/.config/autostart/open_apps.desktop"
    content: |
      [Desktop Entry]
      Type=Application
      Exec=/usr/local/bin/open_apps.sh
      Hidden=false
      NoDisplay=false
      X-GNOME-Autostart-enabled=true
      Name[en_US]=Open Apps
      Name=Open Apps
      Comment[en_US]=Opens terminal and Firefox on specific workspaces
      Comment=Opens terminal and Firefox on specific workspaces
    mode: '0644'
