--- 
- name: Install Kitty
  community.general.homebrew:
    name:
      - kitty
    state: latest

- name: Meslo Nerd Font installieren
  community.general.homebrew:
      name: font-meslo-lg-nerd-font
      state: present

- name: Create configuration directory
  file:
    path: "{{ ansible_user_dir }}/.config/kitty"
    state: directory
    mode: '0755'

- name: Copy kitty configuration file
  ansible.builtin.copy:
    dest: "{{ ansible_user_dir }}/.config/kitty"
    src: "kitty.conf"
    mode: '0744'

