--- 
- name: "Include macOS tasks"
  include_tasks: "{{ role_path }}/tasks/macos.yaml"
  when: ansible_os_family == "Darwin"

# - name: "Include Debian tasks"
#   include_tasks: "{{ role_path }}/tasks/debian.yaml"
#   when: ansible_os_family == "Debian"
#
# - name: "Include RedHat tasks"
#   include_tasks: "{{ role_path }}/tasks/redhat.yaml"
#   when: ansible_os_family == "RedHat"
#
# - name: "Include Arch Linux tasks"
#   include_tasks: "{{ role_path }}/tasks/archlinux.yaml
#   when: ansible_distribution == "Archlinux"

# General settings
- name: Create configuration directory
  file:
    path: "{{ ansible_user_dir }}/.config/kitty"
    state: directory
    mode: '0755'

- name: Copy kitty configuration file
  ansible.builtin.copy:
    dest: "{{ ansible_user_dir }}/.config/kitty"
    src: "kitty.conf"
    mode: '0744'

