--- 
- name: Create a directory if it does not exists
  ansible.builtin.file:
    path: "{{ ansible_user_dir }}/i3"
    state: directory
    mode: '0755'

- name: Copy i3 config
  ansible.builtin.copy:
    dest: "{{ ansible_user_dir }}/i3/config"
    src: "config"

- name: Copy Xressources
  ansible.builtin.copy:
    dest: "{{ ansible_user_dir }}/.Xressources"
    src: ".Xresources"
