--- 
- name: Install
  ansible.builtin.package:
    name:
        - ttf-meslo-nerd-font-powerlevel10k
        - zsh-theme-powerlevel10k
    state: latest
  become: yes

- name:  Copy p10k style file
  ansible.builtin.copy:
    dest: "{{ ansible_user_dir }}/.p10k.zsh"
    src: ".p10k.zsh"
    mode: '0644'
