--- 
- name: "Include macOS tasks"
  include_tasks: "{{ role_path }}/tasks/macos.yaml"
  when: ansible_os_family == "Darwin"

# - name: "Include Debian tasks"
#   include_tasks: "{{ role_path }}/tasks/debian.yaml"
#   when: ansible_os_family == "Debian"
#
# - name: "Include RedHat tasks"
#   include_tasks: "{{ role_path }}/tasks/redhat.yaml"
#   when: ansible_os_family == "RedHat"
#
# - name: "Include Arch Linux tasks"
#   include_tasks: "{{ role_path }}/tasks/archlinux.yaml"
#   when: ansible_distribution == "Archlinux"

# General settings
- name: Ensure managed-repos directory exists
  file:
    path: "{{ ansible_user_dir }}/managed-repos"
    state: directory

- name: Clone or update the fzf-git repository
  git:
    repo: https://github.com/junegunn/fzf-git.sh.git
    dest: "{{ ansible_user_dir }}/managed-repos/fzf-git.sh"
    update: yes
