---
- name: "Include macOS tasks"
  include_tasks: "{{ role_path }}/tasks/macos.yaml"
  when: ansible_os_family == "Darwin"

# - name: "Include Debian tasks"
#   include_tasks: "{{ role_path }}/tasks/debian.yaml"
#   when: ansible_os_family == "Debian"
#
# - name: "Include RedHat tasks"
#   include_tasks: "{{ role_path }}/tasks/redhat.yaml"
#   when: ansible_os_family == "RedHat"
#
# - name: "Include Arch Linux tasks"
#   include_tasks: "{{ role_path }}/tasks/archlinux.yaml"
#   when: ansible_distribution == "Archlinux"

# General settings
- name: Set diff.colorMoved
  community.general.git_config:
    name: diff.colorMoved
    scope: global
    value: zebra

- name: Set fetch.prune
  community.general.git_config:
    name: fetch.prune
    scope: global
    value: true

- name: Set init.defaultBranch
  community.general.git_config:
    name: init.defaultBranch
    scope: global
    value: main

# - name: Set user.email
#   community.general.git_config:
#     name: user.email
#     scope: global
#     value: "{{ git_user_email }}"
#   no_log: true
#
# - name: Set user.name
#   community.general.git_config:
#     name: user.name
#     scope: global
#     value: "{{ git_user_name }}"

- name: Set store credentials
  community.general.git_config:
    name: credential.helper
    value: store
    scope: global

- name: Set alias status
  community.general.git_config:
    name: alias.st
    scope: global
    value: status

- name: Set alias checkout
  community.general.git_config:
    name: alias.co
    scope: global
    value: checkout

- name: Set alias commit
  community.general.git_config:
    name: alias.ci
    scope: global
    value: commit

- name: Set alias branch
  community.general.git_config:
    name: alias.br
    scope: global
    value: branch

- name: Set core autocrlf
  community.general.git_config:
    name: core.autocrlf
    scope: global
    value: false

- name: Set core editor
  community.general.git_config:
    name: core.editor
    scope: global
    value: nvim

- name: Set core preloadindex
  community.general.git_config:
    name: core.preloadindex
    scope: global
    value: true

- name: Set core fscache
  community.general.git_config:
    name: core.fscache
    scope: global
    value: true

- name: Set color
  community.general.git_config:
    name: color.ui
    scope: global
    value: true

