--- 
- name: "Include macOS tasks"
  include_tasks: "{{ role_path }}/tasks/macos.yaml"
  when: ansible_os_family == "Darwin"

# - name: "Include Debian tasks"
#   include_tasks: "{{ role_path }}/tasks/debian.yaml"
#   when: ansible_os_family == "Debian"
#
# - name: "Include RedHat tasks"
#   include_tasks: "{{ role_path }}/tasks/redhat.yaml"
#   when: ansible_os_family == "RedHat"
#
# - name: "Include Arch Linux tasks"
#   include_tasks: "{{ role_path }}/tasks/archlinux.yaml"
#   when: ansible_distribution == "Archlinux"

# General settings
- name: Copy .tmux.conf
  ansible.builtin.copy:
    dest: "{{ ansible_user_dir }}/.tmux.conf"
    src: "tmux.conf"

# - name: Copy .gitmux.conf
#   ansible.builtin.copy:
#     dest: "{{ ansible_user_dir }}/.gitmux.conf"
#     src: "gitmux.conf"

- name: Check if TPM directory exists
  stat:
    path: "{{ ansible_user_dir }}/.tmux/plugins/tpm"
  register: tpm_dir

- name: Clone TPM if not already installed
  git:
    repo: https://github.com/tmux-plugins/tpm.git
    dest: "{{ ansible_user_dir }}/.tmux/plugins/tpm"
  when: not tpm_dir.stat.exists

- name: Ensure TPM script is executable
  file:
    path: "{{ ansible_user_dir }}/.tmux/plugins/tpm/tpm"
    mode: "0755"
  when: tpm_dir.stat.exists
