--- 
- name: Install
  ansible.builtin.package:
    name:
      - tmux
    state: latest
  become: yes

- name: Copy init.lua
  ansible.builtin.copy:
    dest: "{{ ansible_user_dir }}/.tmux.conf"
    src: ".tmux.conf"
