--- 
- name: Install
  community.general.homebrew:
    name:
      - tmux
    state: latest

- name: Copy .tmux.conf
  ansible.builtin.copy:
    dest: "{{ ansible_user_dir }}/.tmux.conf"
    src: ".tmux.conf"
