--- 
- name: Dependencies
  ansible.builtin.package:
    name:
      - texlive-binextra
    state: latest
  become: yes

- name: Install
  ansible.builtin.package:
    name:
      - pandoc-cli
    state: latest
  become: yes
