---
- name: Dependencies
  community.general.homebrew:
    name:
      - curl
      - wget
      - tree-sitter
      - unzip
      - prettier
      - shfmt
      - shellcheck
      - luarocks
      - ripgrep
    state: latest

- name: Install Node.js and npm dependencies
  community.general.homebrew:
    name: node
    state: latest

- name: Install
  community.general.homebrew:
    name:
      - neovim
    state: latest
